server:
  port: 8081
spring:
  application:
    name: CUSTOMER-WS
  datasource:
    password: sa
    url: jdbc:h2:mem:testdb
    username: sa
    
  h2:
    console:
      enabled: true
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
